### ISSUE TITLE
Figure 03: Health Status between the Elderly who Have Kids and No Kids

### ISSUE THREAD

**Issue by VladimirCao** [VladimirCao/assignment04#13]
Hi, Xiaolin. Awesome work on the previous figures 1 and 2. Now let's get started with figure 3. For figure 3, we have following tasks to do:

- [x] We need to do some data manipulation and generate some new variables of interest that we can use for our graph.
- [x] As we discussed before, we use *geom_col* for this graph.
- [x] Add labels and make the graph seem better.
- [x] Write the analysis.

**Comment by xiaolin1019** [comment]
Done!
