### ISSUE TITLE
Figure 01: Average Health Scores by Sex

### ISSUE THREAD

**Issue by VladimirCao** [VladimirCao/assignment04#6]
Hi Xiaolin, we have successfully finished data cleaning part. Let's get started with the amazing figure 01 part! We have the following tasks:

- [x] We should get further step into the variables of three types of health scores.
- [x] For the first graph, as we discussed before, we plan to create a *geom_line* plot.
- [x] Add title and theme to it.
- [x] Write the analysis.

**Comment by xiaolin1019** [comment]
good
